---
name: CD

on:
  push:
    tags:
      - v*

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Go Continuous Delivery
    uses: neticdk/shared-github-actions/.github/workflows/go-cd.yaml@5a8088d825acc21e9ba96ffe04389e96301f60b7 # v0.8.1
    secrets: inherit
