---
name: CI

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - main

permissions:
  actions: write
  contents: write
  packages: write
  pull-requests: write

jobs:
  test:
    name: Go Continuous Integration
    uses: neticdk/shared-github-actions/.github/workflows/go-ci.yaml@6b06079b6d743217648e9829e34db83489a9954c # v0.4.4
    secrets: inherit
