---
name: CI

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - main

permissions:
  actions: write
  contents: write
  packages: write
  pull-requests: write

jobs:
  test:
    name: Go Continuous Integration
    uses: neticdk/shared-github-actions/.github/workflows/go-ci.yaml@f1079054f30f35798c8c9c0d38d5b7695704d5e8 # v0.4.1
    secrets: inherit
