---
name: CI

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - main

permissions:
  actions: write
  contents: write
  packages: write
  pull-requests: write

jobs:
  test:
    name: Go Continuous Integration
    uses: neticdk/shared-github-actions/.github/workflows/go-ci.yaml@199863e78bf5e024e813efba9ecf80642b503930 # v0.6.2
    secrets: inherit
