name: Compile & Test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          # get the latest stable version from the go-versions repository
          # manifest:
          # https://github.com/actions/go-versions/blob/main/versions-manifest.json
          go-version: 'stable'

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -v ./... -vet=all
